#!/usr/bin/env python2.7
# -*- coding:UTF-8 -*-2
u"""const.py

Copyright(c)2019 Yukio Kuro
This software is released under BSD license.

定数モジュール。
複数モジュールで共有する変数。
*インベントリに関する変数を変えた場合、データロードに失敗する。PLAYER_NUMBERなど。
"""
# ---- System ----
CAPTION = u"STAR SEEKER"
COPYRIGHT = u"Copyright (c) 2019 Yukio Kuro"
IS_MULTIPROCESSING = True
BASE_SCREEN_SIZE = 320, 240
MAIN_SCREEN_SIZE = 640, 480
FRAME_RATE = 60
FRAME_DELAY = FRAME_RATE/15
GRID_SHIFT = 4
GRID = 1 << GRID_SHIFT
NEXT_WINDOW_SIZE = GRID << 1, GRID << 1
SYSTEM_CHAR_SIZE = 10
EFFECT_CHAR_SIZE = 12
MODE_CHAR_SIZE = 32
SPEED_TEXTS = "VeryFast", "Fast", "Normal", "Slow", "VerySlow"
FIELD_SIZE_TEXTS = "Small", "Normal", "Large", "VeryLarge"
EXIT_STATUS = -1
IGNORE_STATUS = 0
MODE_SELECT_STATUS = 1
DUEL_SELECT_STATUS = 2
DUEL_STATUS = 3
ENDLESS_STATUS = 4
VERSUS_SELECT_STATUS = 5
VERSUS_STATUS = 6
CUSTOM_STATUS = 7
INTERVAL_STATUS = 8
RESULT_STATUS = 9
BG_DICT = {
        0: "boneyard", 1: "ruins", 2: "night_city", 3: "ruins",
        4: "night_city", 5: "night_city", 6: "boneyard", 7: "catacombe",
        8: "catacombe"}
# ---- Game ----
PLAYER_NUMBER = 8
PRESS_POINT = 100
PRESS_LIMIT = PRESS_POINT << 4
EFFECT_ACCUMULATE_LIMIT = 4
SINGLE_SCORE = 100
HALF_SCORE = SINGLE_SCORE >> 1
QUARTER_SCORE = SINGLE_SCORE >> 2
DOUBLE_SCORE = SINGLE_SCORE << 1
SOLID_PRESS_LEVEL = 4
ADAMANT_PRESS_LEVEL = 8
STAR_ENERGY_SHIFT = 2
STAR_ENERGY = 1 << STAR_ENERGY_SHIFT
NAME_LIMIT = 10
RANK_LIMIT = 3
ENDLESS_LIMIT = 40
ENDLESS_INTRVAL = 5
SKILL_CAPACITY = 8
DECK_CAPACITY = 16
# ---- Name ----
ALTAIR_NAME = u"アルタイル"
CORVUS_NAME = u"コーヴァス"
NOVA_NAME = u"ノヴァ"
SIRIUS_NAME = u"シリウス"
CASTOR_NAME = u"カストル"
PLUTO_NAME = u"プルート"
REGULUS_NAME = u"レグルス"
LUCIFER_NAME = u"ルキフェル"
NEBULA_NAME = u"ネビュラ"
WARRIOR_ROLE = u"ウォーリア"
WIZARD_ROLE = u"ウィザード"
SEEKER_ROLE = u"シーカー"
ROYAL_ROLE = u"ロイヤル"
MONSTER_ROLE = u"モンスター"
SUMMON_TYPE = u"サモン"
FUSIONED_TYPE = u"フュージョン"
SORCERY_TYPE = u"ソーサリー"
PILED_TYPE = u"パイル"
SHIELD_TYPE = u"シールド"
JOKER_TYPE = u"ジョーカー"
SWORD_CATEGORY = u"剣"
WAND_CATEGORY = u"杖"
HEAVY_CATEGORY = u"重武器"
MISSILE_CATEGORY = u"飛び道具"
WEAPON_CATEGORYS = (
    SWORD_CATEGORY, WAND_CATEGORY,
    HEAVY_CATEGORY, MISSILE_CATEGORY)
HAT_CATEGORY = u"帽子"
HELMET_CATEGORY = u"兜"
CROWN_CATEGORY = u"王冠"
HEAD_CATEGORYS = HAT_CATEGORY, HELMET_CATEGORY, CROWN_CATEGORY
CLOTHES_CATEGORY = u"服"
ARMOR_CATEGORY = u"鎧"
ROBE_CATEGORY = u"ローブ"
BODY_CATEGORYS = CLOTHES_CATEGORY, ARMOR_CATEGORY, ROBE_CATEGORY
RING_CATEGORY = u"指輪"
ACCESSORY_CATEGORYS = RING_CATEGORY,
BEAST_TRIBE = u"獣"
SKY_TRIBE = u"飛行"
ALCHMIC_TRIBE = u"錬金生物"
REGULAR_TRIBES = BEAST_TRIBE, SKY_TRIBE, ALCHMIC_TRIBE
UNDEAD_TRIBE = u"不死"
DRAGON_TRIBE = u"竜"
ELEMENTAL_TYPES = u"木", u"火", u"土", u"金", u"水", u"月", u"太陽"
FIRE_EATER_SKILL_NAME = u"ファイアイーター"
ICE_PICKER_SKILL_NAME = u"アイスピッカー"
ACID_ERASER_SKILL_NAME = u"アシッドイレーザー"
STONE_BREAKER_SKILL_NAME = u"ストーンブレーカー"
POWER_STROKE_SKILL_NAME = u"パワーストローク"
EXORCIST_SKILL_NAME = u"エクソシスト"
PHANTOM_THIEF_SKILL_NAME = u"ファントムシーフ"
SOUL_EAT_SKILL_NAME = u"ソウルイート"
VAMPIRE_SKILL_NAME = u"ヴァンピール"
REVERSE_SORCERY_SKILL_NAME = u"リバースソーサリー"
ANTI_SUMMONING_SKILL_NAME = u"アンチサモーニング"
COMPLETE_ASSIST_SKILL_NAME = u"コンプアシスト"
PURIFY_SKILL_NAME = u"ピュリファイ"
DOUBLE_SPELL_SKILL_NAME = u"ダブルスペル"
ROB_CARD_SKILL_NAME = u"ロブカード"
SHEPHERD_SKILL_NAME = u"シェパード"
FALCONER_SKILL_NAME = u"ファルコナー"
ALCHMIST_SKILL_NAME = u"アルケミスト"
NECROMANCER_SKILL_NAME = u"ネクロマンサー"
DRAGON_MASTER_SKILL_NAME = u"ドラゴンマスター"
HALF_JUPITER_SKILL_NAME = u"ハーフジュピター"
HALF_MARS_SKILL_NAME = u"ハーフマーズ"
HALF_SATURN_SKILL_NAME = u"ハーフサターン"
HALF_VENUS_SKILL_NAME = u"ハーフヴェヌス"
HALF_MERCURY_SKILL_NAME = u"ハーフメルクリー"
MOON_CHILD_SKILL_NAME = u"ムーンチャイルド"
SON_OF_SUN_SKILL_NAME = u"サンオブサン"
SAFETY_SKILL_NAME = u"セーフティ"
LIFE_BOOST_SKILL_NAME = u"ライフブースト"
MIGHTY_SKILL_NAME = u"マイティ"
TOUGHNESS_SKILL_NAME = u"タフネス"
SPEEDSTER_SKILL_NAME = u"スピードスター"
SWORD_EQUIP_SKILL_NAME = SWORD_CATEGORY+u"装備"
WAND_EQUIP_SKILL_NAME = WAND_CATEGORY+u"装備"
HEAVY_EQUIP_SKILL_NAME = HEAVY_CATEGORY+u"装備"
MISSILE_EQUIP_SKILL_NAME = MISSILE_CATEGORY+u"装備"
HAT_EQUIP_SKILL_NAME = HAT_CATEGORY+u"装備"
HELMET_EQUIP_SKILL_NAME = HELMET_CATEGORY+u"装備"
ARMOR_EQUIP_SKILL_NAME = ARMOR_CATEGORY+u"装備"
ROBE_EQUIP_SKILL_NAME = ROBE_CATEGORY+u"装備"
DARK_FORCE_SKILL_NAME = u"ダークフォース"
# ---- Skill ----
ATTACK_SKILL_TYPE = "Attack"
DEFENCE_SKILL_TYPE = "Defense"
SUSTAIN_SKILL_TYPE = "Sustain"
BASIC_NAMES = "Normal#Solid#Adamant"
STAR_NAMES = "Jupiter#Mars#Saturn#Venus#Mercury#Moon#Sun"
SHARD_NAMES = "Life#Power#Protect#Speed"
KEY_NAMES = "BronzeKey#SilverKey#GoldKey"
CHEST_NAMES = "IronChest#BronzeChest#SilverChest#GoldChest"
CARD_NAMES = "Summon#Sorcery#Shield"
ITEM_NAMES = str(
    STAR_NAMES+"#"+SHARD_NAMES+"#" +
    KEY_NAMES+"#"+CHEST_NAMES+"#"+CARD_NAMES)
SLIME_NAMES = "Slime#Tired"
IRREGULAR_NAMES = "Ruined#Magma#Ice#Matango#Acid#Poison#Stone"
DEMON_NAMES = "Gargoyle#BlockEater#BlockDemon#ArchDemon"
GHOST_NAMES = "RIP#FireGhost#IceGhost#PoisonGhost"
MIMIC_NAMES = "BronzeMimic#SilverMimic#GoldMimic#PandoraMimic"
LOCKED_NAMES = str(MIMIC_NAMES+"#BronzeChest#SilverChest#GoldChest")
MAGMA_EFFECT = "Magma##Normal"
ICE_EFFECT = "Ice##Normal#Solid"
STONE_EFFECT = str("Stone##"+BASIC_NAMES)
MATANGO_EFFECT = str("Matango##"+BASIC_NAMES)
ACID_EFFECT = str("Acid##"+BASIC_NAMES)
POISON_EFFECT = str("Poison##Normal")
JUPITER_EFFECT = str("Jupiter##"+BASIC_NAMES)
MARS_EFFECT = str("Mars##"+BASIC_NAMES)
SATURN_EFFECT = str("Saturn##"+BASIC_NAMES)
VENUS_EFFECT = str("Venus##"+BASIC_NAMES)
MOON_EFFECT = str("Moon##"+BASIC_NAMES)
SUN_EFFECT = str("Sun##"+BASIC_NAMES)
LIFE_EFFECT = str("Life##"+BASIC_NAMES)
POWER_EFFECT = str("Power##"+BASIC_NAMES)
PROTECT_EFFECT = str("Protect##"+BASIC_NAMES)
SPEED_EFFECT = str("Speed##"+BASIC_NAMES)
SLIME_EFFECT = str("Slime##"+BASIC_NAMES)
BLOCK_EATER_EFFECT = str("BlockEater##"+BASIC_NAMES)
FORCE_CRACK = 0b1
UNLOCK_CRACK = 0b10
TREASURE_CRACK = 0b100
FIRE_EATER_CRACK = 0b1000
ICE_PICKER_CRACK = 0b10000
ACID_ERASER_CRACK = 0b100000
STONE_BREAKER_CRACK = 0b1000000
POWER_CRACK = 0b10000000
EXORCIST_CRACK = 0b100000000
# ---- Cell ----
LOW_MALIGNANCY = 1
MID_MALIGNANCY = LOW_MALIGNANCY << 1
HIGH_MALIGNANCY = LOW_MALIGNANCY << 2
WHITE_TARGET_NUMBER = 0
RED_TARGET_NUMBER = 1
ORANGE_TARGET_NUMBER = 5
YELLOW_TARGET_NUMBER = 2
GREEN_TARGET_NUMBER = 3
BLUE_TARGET_NUMBER = 6
PURPLE_TARGET_NUMBER = 4
# ---- Piece ----
SINGLE_PRUNING = 0
HALF_PRUNING = 1
QUARTER_PRUNING = 2
CENTER = 0, 0
UP = 0, -1
RIGHT = 1, 0
DOWN = 0, 1
LEFT = -1, 0
UP_RIGHT = 1, -1
UP_LEFT = -1, -1
DOWN_RIGHT = 1, 1
DOWN_LEFT = -1, 1
A0 = 0
A90 = 1
A180 = 2
A270 = 3
UNROTATABLE = 0
ROTATABLE = 1
REVERSIBLE = 2
SHIFTED = 3
# ---- Command ----
EXIT_COMMAND = "."
UP_COMMAND = "W"
LEFT_COMMAND = "A"
RIGHT_COMMAND = "D"
DOWN_COMMAND = "S"
DECISION_COMMAND = "!"
CANCEL_COMMAND = "?"
HOLD_COMMAND = "&"
REMOVE_COMMAND = "|"
DELETE_COMMAND = "-"
USE_COMMAND = "+"
SELECT_COMMAND = "$"
START_COMMAND = "%"
USE1_COMMAND = "1"
USE2_COMMAND = "2"
USE3_COMMAND = "3"
USE4_COMMAND = "4"
USE5_COMMAND = "5"
USE6_COMMAND = "6"
USE7_COMMAND = "7"
USE8_COMMAND = "8"
VOLUMEUP_COMMAND = ">"
VOLUMEDOWN_COMMAND = "<"
MUTE_COMMAND = "_"
# ---- Color ----
WHITE = "0xFFFFFF"
GRAY = "0x808080"
BLACK = "0x101010"
RED = "0xFF0000"
ORANGE = "0xFF8000"
YELLOW = "0xFFFF00"
YELLOW_GREEN = "0x80FF00"
GREEN = "0x00FF00"
VIRIDIAN = "0x00FF80"
GREEN_BLUE = "0x0080FF"
CYAN = "0x00FFFF"
BLUE = "0x0000FF"
PURPLE = "0x8000FF"
MAGENTA = "0xFF00FF"
DARK_RED = "0x800000"
DARK_ORANGE = "0x804000"
DARK_YELLOW = "0x808000"
DARK_YELLOW_GREEN = "0x408000"
DARK_GREEN = "0x008000"
DARK_GREEN_BLUE = "0x008040"
DARK_VIRIDIAN = "0x008040"
DARK_CYAN = "0x008080"
DARK_BLUE = "0x000080"
DARK_MAGENTA = "0x800080"
RAINBOW = (
    DARK_RED, DARK_ORANGE, DARK_YELLOW, DARK_GREEN,
    DARK_CYAN, DARK_BLUE, DARK_MAGENTA, DARK_MAGENTA)
BURNING = RED, ORANGE, YELLOW, GREEN, YELLOW, ORANGE, RED, PURPLE
# ---- Debug ----
IS_OUTPUT = False
IS_FALL_STOP = False
IS_SPACE_MINIMAP = False
IS_WINDOW_TRANSPARENT = False
IS_BLOCK_RANDOM_STEP = False
IS_SP_UNLIMITED = False
PIECE_TEST = ""
